### PR TITLE
Avoid abnormal sdp state when publication/subscription failed

### PR DESCRIPTION
**Pull request by starwarfan**

### CODE REVIEW

**Review by jianjunz — COMMENTED** [review]
Please describe the issue first. Why client still needs to send SDP even `publish` or `subscribe` request is failed?

**Comment by starwarfan** [comment]
> Please describe the issue first. Why client still needs to send SDP even `publish` or `subscribe` request is failed?

At that point, client already calls setLocalDescription, if the operation fails, the state without setRemoteDescription will cause displayed stream paused in chrome.

**Comment by jianjunz** [comment]
As a fallback, you probably just need to `pc.setRemoteDescription(pc.remoteDescription)`.

**Comment by starwarfan** [comment]
> As a fallback, you probably just need to `pc.setRemoteDescription(pc.remoteDescription)`.

The the media section number will mismatch local's since new transceivers added before.

**Comment by jianjunz** [comment]
Okay, should we stop the transceiver and create a new offer to indicate the transceiver is actually not needed anymore?

**Comment by starwarfan** [comment]
> Okay, should we stop the transceiver and create a new offer to indicate the transceiver is actually not needed anymore?

We can't. You don't understand the scenario. Client creates a local offer with media "0 1 2 3" and calls "setLocal", the "2 3" are newly added, if it fails before getting answer, the stream with media "0 1" in browser will stuck. As far as I know, client can't disable media in offer but in answer. In such case, client needs an answer anyway, either from server or generating itself.

**Comment by jianjunz** [comment]
Two concerns here:
>  stream with media "0 1" in browser will stuck.

This is not expected. Negotiated streams are not updated until getting a new answer.

> client can't disable media in offer but in answer.

Stop the transceiver and create a new offer? You can create a new offer even the client's signaling state is `have-local-offer`.

**Comment by starwarfan** [comment]
> Two concerns here:
> 
> > stream with media "0 1" in browser will stuck.
> 
> This is not expected. Negotiated streams are not updated until getting a new answer.
> 
> > client can't disable media in offer but in answer.
> 
> Stop the transceiver and create a new offer? You can create a new offer even the client's signaling state is `have-local-offer`.

`This is not expected` but it happens. The stats is ok but the display is not.
Does anything changes if you create a new offer or setLocalDescription again when you are already `have-local-offer`?
If you do not understand, you should reproduce the issue, start a publication or subscription which is supposed to fail(such as invalid audio/video from) when there're already ongoing subscriptions.
The issue is originally https://github.com/open-webrtc-toolkit/owt-server/issues/750. Though his description is quite inaccurate and hard to understand, follow my instructions.

**Review by jianjunz — APPROVED** [review]
Issue #435 is created for the issue discussed above. This PR could be merged as a workaround.

**Pull request merged**
