### PR TITLE
Eslint cleanup

### PR DESCRIPTION
**Pull request by grgustaf**
I thought it would be easier to review these patches split up, but I could merge them into one.

On the third patch you might prefer a different convention for resolving the warnings.
The fourth patch actually affects functionality and should be more carefully reviewed.

### CODE REVIEW

**Comment by grgustaf** [comment]
@jianjunz, were the CI failures just temporary or did I do something wrong? I'm not sure whether I can restart them?

**Comment by jianjunz** [comment]
Thanks for your PR. As this change adds new dependencies to package.json, I would like @HuaChunbo or @lzhai to confirm that these dependencies are approved by security team. @yanbin7, please take a look at the CI issue.

**Comment by yanbin7** [comment]
@grgustaf , please fix issues found by npm audit
audited 7605 packages in 13.655s

found 15 vulnerabilities (5 low, 6 moderate, 3 high, 1 critical)

  run `npm audit fix` to fix them, or `npm audit` for details

Now using node v8.15.0 (npm v6.4.1)

And there is another build error brought by our test environment network , we will retrigger and finish conference API test

**Comment by jianjunz** [comment]
If vulnerabilities are not introduced in this PR, we could fix them in a separate PR.

**Comment by grgustaf** [comment]
I switched to npm v6.4.1 and I don't see any audit issues when I run that command. But I did need to update the package-lock.json I guess, so I added a new commit. It removed a bunch of 'optional' entries though, I'm not sure the right way to deal with that? It sounds like maybe Windows generates those and Linux doesn't?

**Comment by jianjunz** [comment]
There are some slightly differences between the package-lock.json generated on Windows and Linux. Don't worry about it. CI reported success for your PR.

@HuaChunbo, @lzhai, please take a look at the new dependencies introduced. Thanks.

**Comment by grgustaf** [comment]
@yanbin7, to clarify, I updated to the version you specified and I don't see any issues from running npm audit command.

**Comment by jianjunz** [comment]
@HuaChunbo and @lzhai, please take a look at this PR.

**Comment by jianjunz** [comment]
No response from Chunbo and Jianlin for a long time. QA added code scan into daily build recently. I suppose they'll report license issue if there is anyone discovered.

**Pull request merged**
