### PR TITLE
Remove offerToReceiveAudio/offerToReceiveVideo.

### PR DESCRIPTION
**Pull request by jianjunz**
These are legacy configurations.

### CODE REVIEW

**Comment by jianjunz** [comment]
Fix #154.

**Comment by lzl** [comment]
@jianjunz I use your fix code with v4.2 at Safari. The error at #154 is gone. But it (subscribing mixed stream) still doesn't work and has some warning. Screenshot:

image

**Comment by lzl** [comment]
Safari version is 12.1.1

image

**Comment by lzl** [comment]
I add 1s timeout then subscribe mix stream. It works with this workaround. Maybe this is another bug.

**Comment by jianjunz** [comment]
Thanks for trying this PR and providing feedback. It seems to be a separate issue. We may fix it in another PR.

**Pull request merged**
